import {
  AiFillLinkedin,
  AiFillInstagram,
  AiFillFacebook
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import paulinha from "./assets/paulinha.png"

function App() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
    <div>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="icon" href="./assets/paulinha.png" /> */}
    </div>
    <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
      <section className="min-h-screen">
        <nav className="py-10 mb-10 flex justify-between dark:text-white">
          <h1 className="font-burtons text-xl">Porto Alegre</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className=" cursor-pointer text-2xl"
              />
            </li>
            <li>
              <a
                className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                href={paulinha} download={true}
              >
                Resume
              </a>
            </li>
          </ul>
        </nav>
        <div className="text-center ">
          <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
            Paula D. Toigo
          </h2>
          <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
           Psicóloga
          </h3>
          <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Aluna de graduação no sextos semestre em Psicólogia na Pontifícia Universidade Católica do Rio Grande do Sul (PUCRS)
          </p>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a rel="noreferrer" href="https://www.instagram.com/paula.toigo/" target="_blank"><AiFillInstagram /></a>
            <a rel="noreferrer" href="https://br.linkedin.com/in/paula-toigo-9a778b2a1" target="_blank"><AiFillLinkedin /></a>
            <a rel="noreferrer" href="https://www.facebook.com/profile.php?id=100008260898903&sk=photos" target="_blank"><AiFillFacebook/></a>
          </div>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <img src={paulinha}  className="objetfit" />
          </div>
        </div>
      </section>
      </main>
    </div>
  )
}

export default App
